# Generated by Django 3.0.3 on 2020-02-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shelf_Id', models.IntegerField()),
                ('Shelf_Block', models.CharField(max_length=1)),
                ('Shelf_RowId', models.IntegerField()),
                ('Shelf_Id_Location', models.TextField()),
                ('Shelf_Latitude', models.FloatField()),
                ('Shelf_Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.IntegerField(unique=True)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_category', models.CharField(max_length=50)),
                ('Product_subcategory', models.CharField(max_length=50)),
                ('Product_Price', models.CharField(max_length=50)),
                ('Product_weight', models.FloatField()),
                ('Product_availability', models.BooleanField(default=True)),
                ('Product_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lowe.Shelf')),
            ],
        ),
    ]
