# Generated by Django 3.0.4 on 2020-04-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lowe', '0002_auto_20200409_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_OnClickCount',
            new_name='Product_On_Click_Count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_SubCategory',
            new_name='Product_Sub_Category',
        ),
    ]
